vich_uploader:
    db_driver: orm

    mappings:
        projet_image:
            uri_prefix: /img/projet
            upload_destination: '%kernel.project_dir%/public/img/projet'

        information_image:
            uri_prefix: /img/information
            upload_destination: '%kernel.project_dir%/public/img/information'



    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
